// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DDNS runs the updater in the background and is bound to the frontend, so its exported
 * methods are callable from the settings window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopyHostname puts the full hostname, e.g. home.d.rytrix.com, on the clipboard.
 */
export function CopyHostname(): $CancellablePromise<boolean> {
    return $Call.ByID(133341361);
}

/**
 * Forget deletes the saved hostname and token. The host itself stays registered.
 */
export function Forget(): $CancellablePromise<$models.Status> {
    return $Call.ByID(4158896560);
}

export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(3607245077);
}

export function OpenDashboard(): $CancellablePromise<void> {
    return $Call.ByID(3120799107);
}

/**
 * Save checks the hostname and token with a real update before keeping them.
 */
export function Save(hostname: string, token: string): $CancellablePromise<$models.Status> {
    return $Call.ByID(1251855332, hostname, token);
}

export function SetStartAtLogin(enabled: boolean): $CancellablePromise<$models.Status> {
    return $Call.ByID(4261784013, enabled);
}

/**
 * UpdateNow sends an update even if the IP hasn't changed.
 */
export function UpdateNow(): $CancellablePromise<$models.Status> {
    return $Call.ByID(313798856);
}
