// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DDNS from "./ddns.js";
export {
    DDNS
};

export type {
    Status
} from "./models.js";
