// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is everything the window and tray show.
 */
export interface Status {
    "configured": boolean;
    "hostname": string;
    "domain": string;
    "server": string;
    "ip": string;
    "lastChecked": string;
    "error": string;
    "busy": boolean;
    "startAtLogin": boolean;
    "version": string;
}
